#!/opt/homebrew/bin/gawk -f
function decreasing(a, b) { return (a - b) > 0 }
function abs(v) {return v < 0 ? -v : v}
{
    safe = 1
    init = decreasing($1, $2)
    for (i = 1; i < NF; i++) {
      distance = abs($i - $(i+1))
      if (!(decreasing($i, $(i+1)) == init && distance >= 1 && distance <= 3)) {
        safe = 0
        break
      }
    }
    result += safe
}
END{
  print result
  # 510
}
