#!/opt/homebrew/bin/gawk -f

function abs(v) {return v < 0 ? -v : v}
{
  a[NR] = $1
  b[NR] = $2
}
END {
  asort(a)
  asort(b)
  sum = 0
  for (i = 1; i <= NR; i++) {
    sum += abs(b[i] - a[i])
  }
  print sum
  # 1666427
}

