#!/opt/homebrew/bin/gawk -f

BEGIN {
    FPAT = "mul\\([0-9]+,[0-9]+\\)"
}
{
  for (i = 1; i <= NF; i++) {
    $i = gensub(/mul\(|\)/, "", "g", $i)
    split($i, a, ",")
    # print $i
    sum += a[1] * a[2]
  }
}
END{
  print sum
  # 191183308
}
